import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.1.10"

    id("com.gradleup.shadow") version "9.4.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.io.netty.netty.all)
    implementation(libs.org.yaml.snakeyaml)
    implementation(libs.org.slf4j.slf4j.api)
    implementation(libs.org.apache.logging.log4j.log4j.slf4j.impl)
    implementation(libs.it.unimi.dsi.fastutil)
    implementation(libs.net.kyori.adventure.api)
    implementation(libs.net.kyori.adventure.text.serializer.plain)
    implementation(libs.net.kyori.adventure.text.serializer.legacy)
    implementation(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    implementation(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)

    implementation(libs.org.jetbrains.kotlin.kotlin.reflect)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test.junit)
    compileOnly(libs.org.jetbrains.annotations)
}

tasks.withType<Test> {
    useJUnitPlatform()
}

group = "xyz.nkomarn"
version = "1.0-SNAPSHOT"
description = "Composter"
java.sourceCompatibility = JavaVersion.VERSION_21

kotlin {
    jvmToolchain(21)
}

tasks.withType<KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        freeCompilerArgs.add("-XXLanguage:+ExplicitBackingFields")
    }
}

tasks.named<ShadowJar>("shadowJar") {
    archiveClassifier.set("")
    configurations = listOf(project.configurations.runtimeClasspath.get())
    manifest {
        attributes["Main-Class"] = "kyta.composter.ComposterKt"
        attributes["Multi-Release"] = true
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
